### ISSUE TITLE
Astral Sorcery not using ObjectInputStream in updated 1.12 versions

### ISSUE THREAD

**Issue by jchung01** [dogboy21/serializationisbad#11]
Just going off your config file; it looks like the class `pktSyncConfig` (and thus any remaining use of `ObjectInputStream`) was removed altogether in Astral Sorcery 1.9.2 for MC 1.12. [Relevant commit](https://github.com/HellFirePvP/AstralSorcery/commit/6358ec1af10a7a5aaa79ab01364db117ead9fce7#diff-1949925850ddb0bcdeee0c86ec7e831670e1822c819e39fb81fad4d5e89bb062) with [relevant version number associated with commit](https://github.com/HellFirePvP/AstralSorcery/blob/6358ec1af10a7a5aaa79ab01364db117ead9fce7/src/main/java/hellfirepvp/astralsorcery/AstralSorcery.java#L51).

**Comment by dogboy21** [comment]
Information on affected versions was added in #13
