### ISSUE TITLE
Endercore patched

### ISSUE THREAD

**Issue by tyler489** [dogboy21/serializationisbad#21]
Versions 
EnderCore-1.7.10-0.2.0.40_beta
EnderCore-1.10-0.4.0.36-beta
EnderCore-1.10.2-0.4.1.67-beta
EnderCore-1.12.2-0.5.77
all have a patch in them.

**Comment by tyler489** [comment]
PS according to the devs 1.7 was also affected.

**Comment by dogboy21** [comment]
Information added to the readme as of #37
