### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by SomeOtherCyclist** [dogboy21/serializationisbad#25]
[latest.log](https://github.com/dogboy21/serializationisbad/files/12208415/latest.log)
Having issues with connecting to my server after installing the patch

I installed it as an agent on the server and client (server with the javaagent argument, client with Prism Launcher's 'add agent' button under 'version') but whenever I try to join my server it says that 'a fatal error has occurred' and that the 'connection has been terminated.' I then tried loading it again without the patch on either the server or client, and I am able to connect again without issue.

Pack is Technological Journey 1.2.2, running Forge 14.23.5.2860

**Comment by Einhornyordle** [comment]
Interesting, thanks for reporting, we'll take a look at it. 

> I installed it as an agent on the server and client
> I then tried loading it again without the patch on either the server or client,

Just to be clear, you tried it on both, server and client, and neither, but never on just one side (either client or server)?

**Comment by SomeOtherCyclist** [comment]
Correct, I have tried on neither and both, but not on only one side

**Comment by TheRealTrip** [comment]
I had the same problem - I believe setting it as an agent is for below 1.7 - adding it to the mods folder on both has same effect of patch but allows you to join your server :)

**Comment by dimon7147** [comment]
I've been using serializationisbad v1.3 on Technological Journey v1.2.2 (server side only) for over 2 weeks and have had no connection issues. Today I updated the mod to version 1.4, also no problems (again, mod installed on server side only).

**Comment by Aiidoneus** [comment]
OK. I will mark this as done! Thank you for your response! If there is an issue after close, just reopen it.
