### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by asiekierka** [dogboy21/serializationisbad#28]
What's the license on this mod? I'm aware it's a bit of a hectic time, but this is important for ensuring the mod can be safely utilized and distributed by modpacks in the long term.

**Comment by JuniorWolfgamingDE** [comment]
I need that info too, since nothing about licensing is mentioned. Currently, it doesnt seem to have ANY license at all.
I would just put it under WTFPL tbh, its an important project.

**Comment by asiekierka** [comment]
If it's an important project, don't put it on one of the most legally ambiguous licenses.

**Comment by dogboy21** [comment]
Yeah sorry about that. I was initially planning on releasing it under MIT, but then everything happend..
I will add it later once I get around to it.

**Comment by dogboy21** [comment]
Added MIT license ([0e0d74a](https://github.com/dogboy21/serializationisbad/commit/0e0d74af8fcfc2ec147661b44c524faa745cc39b))
