### ISSUE TITLE
Immersive Aircraft Error

### ISSUE THREAD

**Issue by dimon7147** [dogboy21/serializationisbad#30]
https://pastebin.com/mxUE7XZJ

After installing serializationisbad v1.3, this message appears periodically in the console.

**Comment by Luke100000** [comment]
Immersive Aircraft dev here, I will retire serialization on my side within the next days, that will fix the crash too.

**Comment by Luke100000** [comment]
Immersive Aircraft 0.5.2 for every MC version [no longer contains deserializing](https://github.com/Luke100000/ImmersiveAircraft/commit/a92c41e432777d10779fd08403a5769bff9771db#diff-00e8c908ee4135e34a745d821ec223104a8d08ee10c2f18f6ed5e0d3c1e36eaf) and thus should also work fine with serializationisbad

**Comment by dogboy21** [comment]
Should be fixed with [version 1.4](https://github.com/dogboy21/serializationisbad/releases/tag/1.4)
