### ISSUE TITLE
Break mods

### ISSUE THREAD

**Issue by felipeleite5w** [dogboy21/serializationisbad#32]
hello, I would like to know if the fix you released break bdlib, I only use this mods of the affected list.

**Comment by dogboy21** [comment]
In theory it should not break bdlib or other mods as we tried to add a complete allowlist for all patched mods.
Other than some problem with Immersive Aircraft (#30), we're not aware of our fix breaking anything.

If you find something wrong after applying our fix, feel free to create a new issue for that!

**Comment by felipeleite5w** [comment]
Ok, thanks. How can i know if the mod serializationisbad loaded? I cant find it in mincraft menu modlist

**Comment by dogboy21** [comment]
If you take a look at the log of your server/client, the following lines should be in there somewhere when the mod is loaded correctly:

```
[io.dogboy.serializationisbad.core.SerializationIsBad]: Initializing SerializationIsBad, implementation type: XXXXXX
[io.dogboy.serializationisbad.core.SerializationIsBad]: Using remote config file
[io.dogboy.serializationisbad.core.SerializationIsBad]: Loaded config file
[io.dogboy.serializationisbad.core.SerializationIsBad]:   Blocking Enabled: true
[io.dogboy.serializationisbad.core.SerializationIsBad]:   Loaded Patch Modules: 36
```
