### ISSUE TITLE
Endercore

### ISSUE THREAD

**Issue by felipeleite5w** [dogboy21/serializationisbad#36]
Which version of endercore is fixed? I need for 1.7. 

https://www.curseforge.com/minecraft/mc-mods/endercore/files/4671288 

I found this one updated yesterday. But i dont know if its fixed...

**Comment by SirEndii** [comment]
Yes, that is indeed the fixed patch

> For Ender IO, here are the minimum Ender Core versions with the patch:

> EnderCore-1.7.10-0.2.0.40_beta
> EnderCore-1.10-0.4.0.36-beta
> EnderCore-1.10.2-0.4.1.67-beta
> EnderCore-1.12.2-0.5.77

**Comment by dogboy21** [comment]
Information added to the readme as of #37
