### ISSUE TITLE
Hmmmmmmmm

### ISSUE THREAD

**Issue by AstraKurai** [dogboy21/serializationisbad#4]
![image](https://github.com/dogboy21/serializationisbad/assets/140068564/667867d2-9130-4879-bc5c-8cfbf12d31d7)

**Comment by AstraKurai** [comment]
Fixed

**Comment by dogboy21** [comment]
https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/blob/72307bbebe3b64b49ede2c5324eada5f2c37b220/src/main/java/com/supermartijn642/configlib/ConfigSyncPacket.java#L117

**Comment by AstraKurai** [comment]
i seen that
