### ISSUE TITLE
Singleplayer?

### ISSUE THREAD

**Issue by Taitep** [dogboy21/serializationisbad#40]
Just a question, is this a problem if you play singleplayer? Could not find a better place to ask.

**Comment by KorewaLidesu** [comment]
No, this only affect Multiplayer side
Unless you have connect to server that is affected by this (Which you should stop any minecraft instance and do antivirus scanning)
Just install this if you want a protection just in case you want to join a server.

**Comment by Taitep** [comment]
ok not planning on playing multiplayer moddedearlier then 1.16 thx.

**Comment by Aiidoneus** [comment]
It is OK to ask questions. We want you to be safe more than anything. Let us know if you have more questions.
