### ISSUE TITLE
Beta 1.7.3 crashes

### ISSUE THREAD

**Issue by Niterux** [dogboy21/serializationisbad#41]
I added it as java agent in beta 1.7.3 instance in prism launcher and it crash on startup im not sure what I'm do wrong
https://mclo.gs/FqZC5Iu
This happens with and without my jar mods enabled and without the other java agent I use on beta 1.7.3 ears mod

**Comment by Aiidoneus** [comment]
Can you try the latest release version? https://github.com/dogboy21/serializationisbad/releases/tag/1.4 and tell us if the issue is still there?

**Comment by Niterux** [comment]
it s fixed thank you

**Comment by Niterux** [comment]
it is crashing again nvm
https://mclo.gs/ikRQ72M

**Comment by Niterux** [comment]
it is working again
