### ISSUE TITLE
improve versioning

### ISSUE THREAD

**Issue by ColonelGerdauf** [dogboy21/serializationisbad#50]
I see that the coremod on CurseForge is cluttered with version numbers and yet is absent of critical versions like 1.5.x and 1.6.x

A suggestion is to simply put in as the latest of each sub-type. 1.19 is an oddball, and I believe that 1.16 is also unusual in this approach. Other than that, there is no reason or benefit to put in a supporting version as "1.20" when "1.20.1" automatically supports the version and vice versa.

**Comment by ColonelGerdauf** [comment]
My question is: how many have a non-latest subversion of a legacy Minecraft build? 

On one hand, it seems sensible that a few may have for instance 1.16.4 or 1.12.1, due to forgetting or not bothering to update from when they created the instance. At the same time though, I am not sure how many have done so and have not moved on to later versions and sub-versions. This would, in my view, fall into a tiny portion of casual Minecraft players.

**Comment by dogboy21** [comment]
Just fyi, as of version 1.4 on Curseforge, I only added the latest patch versions to the list of supported game versions.
Let's see how it turns out.

**Comment by ColonelGerdauf** [comment]
You might want to add in 1.19.3 and 1.19.2, because of the fact that they stand out in breaking compatibility versus 1.19.4.
