### ISSUE TITLE
Break The Mod DynamX

### ISSUE THREAD

**Issue by Sarocesch** [dogboy21/serializationisbad#52]
The mod dynamx is broken by this the mod dynamx is safe in itself but it seems to be blocked

**Comment by Bennyboy1695** [comment]
Do you have logs or anything showing how its broken ?

**Comment by Sarocesch** [comment]
log just unfortunately not I would have to look 

but to understand what the error is you need to know what DynamX does 

DynamX is a vehicle mod with realistic physics 
the problem now is that when you install packs for the mod there is a way to protect them and then the last data is downloaded when you start the game 
and this process no longer works and crashes

**Comment by Sarocesch** [comment]
yes in version 3.3 this works in version 4.0.0 it does not load the content packages and then it stays in this screen 

![image](https://github.com/dogboy21/serializationisbad/assets/91789564/3f059192-b8ff-49d0-b884-227f8d474222)

**Comment by Sarocesch** [comment]
ohh if I wait longer it also crashes second I send the log

**Comment by Sarocesch** [comment]
![image](https://github.com/dogboy21/serializationisbad/assets/91789564/28929e97-5bdb-4cc3-b8b2-1b921ca4ddb6)

![image](https://github.com/dogboy21/serializationisbad/assets/91789564/427b4f07-78de-462b-a77e-820d77ca9ca9)

![image](https://github.com/dogboy21/serializationisbad/assets/91789564/f89e752f-69fc-498b-9aa3-cac0ae97f8db)




[latest.log](https://github.com/dogboy21/serializationisbad/files/12254496/latest.log)

**Comment by Bennyboy1695** [comment]
That issue has nothing to do with SerializationIsBad. Your issue seems to be that you are unable to reach the download website for the mods addons. I would suggest making an issue with the mod maker of DynamX or asking in their discord.

**Comment by Sarocesch** [comment]
I'm in contact with the developers they say it's SerializationIsBad because the mod somehow blocks something

I tried it without the mod and it worked without problems 

and the creators say it's not their mod but SerializationIsBad

**Comment by Bennyboy1695** [comment]
The mod wont change anything unless its specified in the config. And when it does patch something it announces it in the log. I didnt see a patch announced in your log from SerializationIsBad i was also able to run the mod, the basic addon pack and Serializationisbad myself with 0 issues

**Comment by Sarocesch** [comment]
ok this is very weird but thanks for the quick reply
