### ISSUE TITLE
Some clarifications in the mod list

### ISSUE THREAD

**Issue by ColonelGerdauf** [dogboy21/serializationisbad#57]
In the list of affected mods, I am left confused as to what is affected, what is not affected, and where it has been patch.

For example, Reborn Core; the parameter of affected version is a bit hard to read, mainly due to the use of equality symbols. In addition, in my rudimentary research, it appeared that the 1.12 version has been patched, at least a while ago, but that falls within the written parameter of affected mod versions.

Also, a semantic correction for Thaumic Tinkerer's fixed version - the MC version is encapsulated with the mod version when it shouldn't have been. In addition, with the affected versions "Mod Minecraft" can be simplified to "Minecraft".

**Comment by Aiidoneus** [comment]
I will see if I can make things a bit clearer on that front. A lot of the list was copied from what we originally had. I will be making some tweaks later today hopefully
