### ISSUE TITLE
Question: Are the following mods affected? (i have latest version of forge)

### ISSUE THREAD

**Issue by aduud21** [dogboy21/serializationisbad#60]
https://modrinth.com/mod/xaeros-minimap
https://modrinth.com/mod/starlight-forge
https://modrinth.com/mod/not-enough-animations
https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge
https://modrinth.com/mod/ferrite-core
https://modrinth.com/mod/entityculling
https://www.curseforge.com/minecraft/mc-mods/let-sleeping-dogs-lie

Mod file names i have (should have version number)
```
entityculling-forge-1.6.2-mc1.20
ferritecore-6.0.0-forge
invhud.forge.1.20.1-3.4.15
LetSleepingDogsLie-1.20.1-Forge-1.2.0
preview_OptiFine_1.20.1_HD_U_I6_pre5
notenoughanimations-forge-1.6.4-mc1.20
starlight-1.1.2+forge.1cda73c
Xaeros_Minimap_23.6.0_Forge_1.20
```

Photo version:
![Screenshot 2023-08-03 191759](https://github.com/dogboy21/serializationisbad/assets/74877817/d3ebd847-26cc-4217-9f97-f3359060d8bb)

My FORGE version (Latest)
![Screenshot 2023-08-03 190521](https://github.com/dogboy21/serializationisbad/assets/74877817/8f508017-e410-4097-8391-6b72760d1740)

i'd like to know if any of the mods above are vulnerable to this attack.

i have installed https://modrinth.com/mod/serializationisbad

(i have checked https://github.com/dogboy21/serializationisbad/blob/master/docs/mods.md)

My minecraft JVM arguments are:
`-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx8G -Xms8G -javaagent:C:\Users\cedri\AppData\Roaming\.minecraft\mods\serializationisbad-1.3.jar`

**Comment by dogboy21** [comment]
Since all of the mods (except Xaeros Minimap) are client-side only, they should be safe.
Xaeros Minimap also doesn't use the vulnerable class so it is also safe.

**Comment by aduud21** [comment]
> Since all of the mods (except Xaeros Minimap) are client-side only, they should be safe. Xaeros Minimap also doesn't use the vulnerable class so it is also safe.

Thanks for letting me know :D
