### ISSUE TITLE
Server hang seemingly caused by the serializationisbad javaagent

### ISSUE THREAD

**Issue by CyanRyan** [dogboy21/serializationisbad#68]
Ran my server for weeks straight with no issues. Changed/updated nothing at all except the javaagent jar, a day or so later this pops up.
[crash-2023-08-10_23.02.29-server.txt](https://github.com/dogboy21/serializationisbad/files/12318348/crash-2023-08-10_23.02.29-server.txt)

**Comment by dogboy21** [comment]
This crash looks unrelated to SIB so it is probably caused by something else.
