### ISSUE TITLE
RebornCore patched versions available

### ISSUE THREAD

**Issue by AzureAqua** [dogboy21/serializationisbad#7]
See https://github.com/TechReborn/RebornCore/security/advisories/GHSA-r7pg-4xrf-7mrm

**Comment by jchung01** [comment]
I would suggest denoting specifically the versions that fixed the patch in each MC version as mentioned in the table under "Patches" in that link. I think just "<4.7.3" could be misleading as that seems to be referencing 1.16 versions only even though patches were released in 1.15 and 1.12.
