### ISSUE TITLE
JourneyMap on the list

### ISSUE THREAD

**Issue by mysticdrew** [dogboy21/serializationisbad#8]
The class referenced in the json 
![image](https://github.com/dogboy21/serializationisbad/assets/5459941/aa1c56f9-14ab-4bdf-a9e4-8cff5d637b9a)

Only existed in 1.12.2-5.5.x versions, as network was completely rewritten in 5.6.x versions. 

Secondly, the class referenced in the json does not use `ObjectInputStream`. We have never used that class in any versions as far as I am aware. 
These are the imports for that class. 
![image](https://github.com/dogboy21/serializationisbad/assets/5459941/e0e2c1b7-b9c4-4bb6-ad32-14b523c4dad6)

I am confused why JourneyMap is even on this list? How did you detect it?

**Comment by dogboy21** [comment]
The jar I looked at was `journeymap-1.16.5-5.7.1.jar`:

![image](https://github.com/dogboy21/serializationisbad/assets/10376793/10da5f50-7978-4320-97ec-b0ad4974a6d7)

But as I already mentioned in #6 and as of [5ba2357](https://github.com/dogboy21/serializationisbad/commit/5ba2357c4ef4e8bed4f5a041dd4fc6922656229c) in the readme as well, the listed mods just mean that there was at least one vulnerable version.

> Because of the rushed announcement, we are currently unable to give exact version ranges of affected mods. If you want to help out with that, feel free to contribute to this list.

If anyone can provide some more insights into the exact versions that were affected for these mods, that would be great!

**Comment by slava110** [comment]
I can confirm that in the latest 1.12 version of the mod this issue doesn't exist (journeymap-1.12.2-5.7.1)
That's the class on your screenshot:
![image](https://github.com/dogboy21/serializationisbad/assets/26705162/314551cb-1373-4e71-8b42-6195cdb81ab1)
For messaging it's using JSON objects:
![image](https://github.com/dogboy21/serializationisbad/assets/26705162/f1bb5675-f36b-446d-8aa6-1a5b31733f57)
So everything should be fine

**Comment by mysticdrew** [comment]
Looks like the class was used was in 5.7.1 for 1.16.5 but was removed in 5.7.2.

**Comment by mysticdrew** [comment]
So 1.16.5-5.7.2 is the fixed version. All other 5.7.1 versions it looks like do not use that class. 
Please update your readme or would you like me to pr the change?
It looks like it was used as a quickfix to get 1.16.x port out the door. And was removed right away in the 5.7.2 lifecycle.

**Comment by LabsZero** [comment]
Dose this effect the Fabric version at all? asking as i'm a pack dev and want to make sure i don't need to update my fabric packs .

**Comment by mysticdrew** [comment]
> Dose this effect the Fabric version at all? asking as i'm a pack dev and want to make sure i don't need to update my fabric packs .

Are you using journeymap 1.16.5-5.7.1

**Comment by LabsZero** [comment]
The pack version is using journeymap-1.18.2-5.8.5-fabric.jar

**Comment by mysticdrew** [comment]
> The pack version is using journeymap-1.18.2-5.8.5-fabric.jar

per the chat above, I think we can conclude that no, it is not effected by your version.

**Comment by mysticdrew** [comment]
![image](https://github.com/dogboy21/serializationisbad/assets/5459941/51b70058-3860-4fe7-bc3a-7af9a0de3576)
