### ISSUE TITLE
1.7.10, 1.12.2... Crash on load

### ISSUE THREAD

**Issue by xJon** [dogboy21/serializationisbad#83]
First reported over https://github.com/xJon/Hexxit-II/issues/230:
`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
https://mclo.gs/d7kVwP0#L71

This is using version 1.5, and has been reported by players who ran the modpack and mod before.

**Comment by EvaLinn** [comment]
I have the same problem, Minecraft version 1.12.2, Mod version 1.3

**Comment by EvaLinn** [comment]
[serializationisbad.json](https://github.com/dogboy21/serializationisbad/files/14622963/serializationisbad.json)
I put this file into config folder, it works

**Comment by spadethrills** [comment]
> [serializationisbad.json](https://github.com/dogboy21/serializationisbad/files/14622963/serializationisbad.json) I put this file into config folder, it works

Confirmed it works for me too. Thanks Eva

**Comment by dogboy21** [comment]
It looks like Github changed their SSL certificate on the raw.githubusercontent.com domain to a new one which isn't trusted in very old Java versions (8u51 in this case).

SiB downloads its config from there if there isn't one locally in the config directory:
 - either `serializationisbad.json`
 - (Versions >= 1.5) or the `serializationisbad-remotecache.json` which gets created after a successful download from Github
 
I'm currently looking for another reliable static file host where I can upload the config file to, which also has a certificate that is trusted by ancient Java versions.

In the meantime, like @EvaLinn already mentioned, adding the file manually to the config directory works as a workaround.

**Comment by dogboy21** [comment]
I just published [version 1.5.1 on Github](https://github.com/dogboy21/serializationisbad/releases/tag/1.5.1) with a changed URL for the remote config.
Could you please check if that resolves the issue on your end as well?

**Comment by EvaLinn** [comment]
> I just published [version 1.5.1 on Github](https://github.com/dogboy21/serializationisbad/releases/tag/1.5.1) with a changed URL for the remote config. Could you please check if that resolves the issue on your end as well?

I don't think I can check this out. That's not me holding a server. I can change it on my side but I don't think it's gonna work

**Comment by dogboy21** [comment]
> I don't think I can check this out. That's not me holding a server. I can change it on my side but I don't think it's gonna work

Updating it only on the client side should work just fine

**Comment by EvaLinn** [comment]
> > I don't think I can check this out. That's not me holding a server. I can change it on my side but I don't think it's gonna work
> 
> Updating it only on the client side should work just fine

I deleted that config file and changed to new version and... Nope, it doesn't work

**Comment by dogboy21** [comment]
Could you send me your game log?

**Comment by EvaLinn** [comment]
[latest.log](https://github.com/dogboy21/serializationisbad/files/14623683/latest.log)

**Comment by EvaLinn** [comment]
> Could you send me your game log?

Lol I noticed, why it says 1.3

**Comment by ThePixelbrain** [comment]
> I can't delete the file because my launcher loads it again :( Modpack in TLauncher. You should ask someone else to help XD

You should update the SerializationIsBad mod to 1.5.1. If your launcher doesn't allow you to do this, there is nothing we can do on our end. (Considering that you're using an illegal cracked version of the game, you should probably just buy the game and use another launcher)

**Comment by EvaLinn** [comment]
> > I can't delete the file because my launcher loads it again :( Modpack in TLauncher. You should ask someone else to help XD
> 
> You should update the SerializationIsBad mod to 1.5.1. If your launcher doesn't allow you to do this, there is nothing we can do on our end. (Considering that you're using an illegal cracked version of the game, you should probably just buy the game and use another launcher)

I have license, but I don't like official Minecraft Launcher. It's much easier for me to make modpacks in TLauncher. And yeah, it doesn't allow me to update the mod

**Comment by MommyHeather** [comment]
> I have license, but I don't like official Minecraft Launcher. It's much easier for me to make modpacks in TLauncher. And yeah, it doesn't allow me to update the mod

Then use something like Prism Launcher. TLauncher is illegal and is known for stealing legitimate accounts. 
There's also the official Modrinth and Curseforge launchers.

**Comment by xJon** [comment]
@dogboy21 Replacing 1.5 with 1.5.1 does not appear to work - https://mclo.gs/zthspOM

**Comment by dogboy21** [comment]
If you already have a `serializationisbad.json` in your config folder, try deleting that before starting the game.

**Comment by xJon** [comment]
@dogboy21 Resetting it appears to work 🎉

**Comment by dogboy21** [comment]
1.5.2, which replaces the old URL with the new one, is now released as well :)
Will also upload it to CF/Modrinth in a few minutes

**Comment by xJon** [comment]
@dogboy21 I can confirm it works :)

**Comment by dogboy21** [comment]
Alright, thank you for testing!

**Comment by felipeleite5w** [comment]
Hey, sorry for the dumb question, but do I need to update the mod or just delete the mod config ? Thanks!

**Comment by Einhornyordle** [comment]
Both

**Comment by dogboy21** [comment]
If you're currently using version 1.4 or above, setting `remoteConfigUrl` in the config to `https://serializationisbad.dogboy.io/serializationisbad.json` should be enough.
Otherwise update to 1.5.2 which already has that fix builtin.
Deleting the config file isn't neccessary with 1.5.2.

**Comment by felipeleite5w** [comment]
Perfect! Thanks
