### ISSUE TITLE
Can someone plz take a look, it is a possible crash with latest version of Tough As Nails!

### ISSUE THREAD

**Issue by Beata-Scheisner-Petersen** [dogboy21/serializationisbad#86]
On MC 1.201, I think SerializationIsBad 1.5 (latest on ATLauncher) craches with Tough As Nails Forge 1.20.1-9.2.0.171.

[crash-2024-12-05_12.43.18-client.txt](https://github.com/user-attachments/files/18023028/crash-2024-12-05_12.43.18-client.txt)

[latest.log](https://github.com/user-attachments/files/18023033/latest.log)

**Comment by dogboy21** [comment]
That is not a bug with SerializationIsBad. I cannot even see that you have SIB installed in your log.
